---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    author: felix
    name: postgres-deployment
spec:
  selector:
    matchLabels:
      name: postgres-deployment
  template:
      metadata:
        name: postgres-pod
        labels:
          name: postgres-deployment
      spec:
        containers:
          - name: postgres
            image: postgres
            ports:
              - containerPort: 5432
            env:
              - name: POSTGRES_PASSWORD
                value: felix
              - name: POSTGRES_USER
                value: myuser
              - name: POSTGRES_DB
                value: mydb
...



